
    create table Guardarropas (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table Guardarropas_Prenda (
        Guardarropas_id bigint not null,
        prendas_id bigint not null
    )

    create table Prenda (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    alter table Guardarropas_Prenda 
        add constraint UK_til88d6visu88gxvmlvo2fe6n  unique (prendas_id)

    alter table Guardarropas_Prenda 
        add constraint FK_til88d6visu88gxvmlvo2fe6n 
        foreign key (prendas_id) 
        references Prenda

    alter table Guardarropas_Prenda 
        add constraint FK_nrxek4uwds8gcxi306dsj85lc 
        foreign key (Guardarropas_id) 
        references Guardarropas
